"""Streamlit page: Home — project overview and navigation."""

from __future__ import annotations

import sys
from pathlib import Path

import streamlit as st

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from src.utils.config import get_config  # noqa: E402

cfg = get_config()
st.set_page_config(page_title="Home", page_icon="🏠", layout="wide")

st.title("🏠 Project Overview")

st.markdown(
    """
    ## Transaction Anomaly Detection Using Unsupervised Learning

    Financial institutions must flag suspicious card transactions without waiting for
    labeled fraud examples, which are scarce, expensive, and quickly outdated as fraud
    patterns evolve. This project builds a complete **unsupervised** anomaly-detection
    pipeline that identifies suspicious transactions **without using fraud labels during
    training** — the `Is Fraud?` label is used exclusively for post-hoc evaluation, never
    for fitting any model.

    ### Business Problem
    Given a stream of transactions described by amount, merchant, timing, and channel,
    rank each transaction by how anomalous its behavioral context is relative to that
    customer's and merchant's typical activity. High-ranked transactions are surfaced to
    a fraud analyst for review — complementing, not replacing, supervised fraud models
    that require labels the business may not yet have for emerging fraud patterns.

    ### Dataset
    [IBM / Kaggle — Credit Card Transactions](https://www.kaggle.com/datasets/ealtman2019/credit-card-transactions)
    (`ealtman2019/credit-card-transactions`): ~24 million synthetic transactions across
    ~2,000 users, generated by IBM's multi-agent transaction simulator.
    """
)

col1, col2 = st.columns(2)
with col1:
    st.markdown(
        """
        ### Methodology
        1. **Validate** raw data against the expected schema
        2. **Clean** — currency parsing, datetime construction, missing values, duplicates, winsorizing
        3. **Engineer** 14 causal behavioral features (customer/merchant/time-based)
        4. **Encode** — frequency-encode categoricals, scale numerics (fit on train only)
        5. **Train** 4 unsupervised models: Isolation Forest, LOF, One-Class SVM, Autoencoder
        6. **Evaluate** against the held-out fraud label (ROC-AUC, AP, precision/recall@k)
        7. **Explain** flagged transactions with permutation importance + per-instance breakdowns
        """
    )
with col2:
    st.markdown(
        """
        ### Engineered Features (14)
        - Customer avg / max transaction amount, transaction count
        - Merchant transaction frequency, merchant diversity
        - Average daily spending, customer activity frequency
        - Weekend / business-hour indicators
        - Time since previous transaction, rolling average amount
        - Transaction velocity (trailing-window count)
        - Amount deviation from customer mean, amount z-score by merchant
        """
    )

st.divider()
st.markdown(
    """
    ### Why no fraud labels during training?
    New fraud patterns emerge before they're labeled, label collection lags real
    transactions by weeks, and a behavior-based anomaly score generalizes to fraud types
    never seen in historical labels. The four unsupervised models each learn a different
    notion of "normal" behavior — isolation depth, local density, kernel-boundary distance,
    and reconstruction error — so no single model's blind spot dominates the system.
    """
)

st.info(
    "Use the sidebar to explore the data, compare model performance, score new "
    "transactions live, or view business-focused anomaly insights."
)